<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Modules\Nearby\Http\Entities\Nearby;

class NearbyFactory extends Factory
{
    protected $model = Nearby::class;

    public function definition(): array
    {
        $nearby_array = [
            'Araz Market',
            'Bravo Market',
            'Bazarstore',
            'Neptun Supermarket',
            'Bolmart',
            'Sədərək Ticarət Mərkəzi',
            'Binə Ticarət Mərkəzi',
            '28 Mall',
            'Gənclik Mall',
            'Metropark',
            'Port Baku Mall',
            'Bakı Dövlət Universiteti',
            'ADA Universiteti',
            'Azərbaycan Texniki Universiteti',
            'Azərbaycan Tibb Universiteti',
            'Bakı Slavyan Universiteti',
            'Nizami Kino Mərkəzi',
            'Azərbaycan Dövlət Akademik Milli Dram Teatrı',
            'Heydər Əliyev Mərkəzi',
            'Bakı Kitab Mərkəzi',
            'Milli Elmlər Akademiyası',
            'Bakı Olimpiya Stadionu',
            'Tofiq Bəhramov Stadionu',
            'Bakı Zooloji Parkı',
            'Atəşgah Məbədi',
            'Yanardağ',
            'İçərişəhər',
            'Qız Qalası',
            'Şəhidlər Xiyabanı',
            'Dağüstü Park',
            'Bakıxanov Parkı',
            'Nərimanov Parkı',
            'Dədə Qorqud Parkı',
            'Dənizkənarı Bulvar',
            'Sahil Parkı',
            'Zabitlər Parkı',
            'Nizami küçəsi',
            'Ticarət küçəsi',
            'Əhmədli metro stansiyası',
            'Nərimanov metro stansiyası',
            'Elmlər Akademiyası metro stansiyası',
            'Gənclik metro stansiyası',
            'Memar Əcəmi metro stansiyası',
            'Neftçilər metro stansiyası',
            'Xalqlar Dostluğu metro stansiyası',
            'İnşaatçılar metro stansiyası',
            'Bakmil metro stansiyası',
            'Bakı Beynəlxalq Avtovağzal',
            'Hava limanı - Heydər Əliyev',
            'Qələbə Dairəsi',
            'Koroğlu Parkı',
            'Park Bulvar',
            'Dostluq Parkı',
            'Şəhriyar Mədəniyyət Mərkəzi',
            'M. F. Axundov adına Milli Kitabxana',
            'Bakı Musiqi Akademiyası',
            'Azərbaycan Milli Konservatoriyası',
            'Kapital Bank',
            'Azərbaycan Beynəlxalq Bankı',
            'AccessBank',
            'Yelo Bank',
            'ABB ATM',
            'Expressbank ATM',
            'DOST Mərkəzi',
            'ASAN Xidmət mərkəzi 1',
            'ASAN Xidmət mərkəzi 5',
            'Azəriqaz ofisi',
            'Azərsu ofisi',
            'Aztelekom ofisi',
            'Azercell satış mərkəzi',
            'Bakcell satış mərkəzi',
            'Nar satış mərkəzi',
            'City Hospital',
            'Medilux Hospital',
            'Kaspian Hospital',
            'LOR Hospital',
            'Yeni Klinika',
            'Respublika Müalicəvi Diaqnostika Mərkəzi',
            'Baku Medical Plaza',
            'Central Hospital',
            'Təcili Tibbi Yardım Mərkəzi',
            'Azərbaycan Respublikası Müdafiə Nazirliyi',
            'Daxili İşlər Nazirliyi',
            'Əmək və Əhalinin Sosial Müdafiəsi Nazirliyi',
            'Təhsil Nazirliyi',
            'Ekologiya və Təbii Sərvətlər Nazirliyi',
            'Qafqaz Universiteti',
            'Khazar University',
            'Western Caspian University',
            'Akkord Ofisi',
            'SOCAR Ofisi',
            'Azərenerji ASC',
            'Azərekspo Mərkəzi',
            'Bakı Ekspo Mərkəzi',
            'Baku Crystal Hall',
            'AF Hotel Aqua Park',
            'Bilgəh Beach Hotel',
            'Amburan Beach Club',
            'Sea Breeze Resort',
            'Shikhov Beach',
            'Xəzər Dənizi sahili',
        ];

        return [
            'name' => $this->faker->randomElement($nearby_array),
            'is_active' => $this->faker->boolean(90),
        ];
    }

}
